export const DYNAMODB_CLIENT_OPTIONS = Symbol('DYNAMODB_CLIENT_OPTIONS');
export const DYNAMODB_MARSHALL_OPTIONS = Symbol('DYNAMODB_MARSHALL_OPTIONS');
export const DYNAMODB_UNMARSHALL_OPTIONS = Symbol('DYNAMODB_UNMARSHALL_OPTIONS');
